baseurl = "https://meng.cat"
languageCode = "zh_cn"
language = "zh-Hans"
title = "日积月累"
theme = "whiteplain"
publishDir = "docs"
copyright = "&copy; 2018 |  <a href=\"https://github.com/taikii/whiteplain.git\" target=\"_blank\">whiteplain theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

pygmentsCodefences = true #高亮markdown的代码块
pygmentsCodefencesGuessSyntax = true #高亮markdown中没有标注语言的代码块
pygmentsStyle = 'github' #高亮主题
pygmentsUseClasses=true


[params]
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "JerryWang"
  # Gravatar or Abatar image
  gravatar = "gaediy@gmail.com"
  #avatar = "/path/to/avatar"

  email = "gaediy@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "分类"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "标签"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "关于"
  identifier = "about"
  url = "/about/"
  weight = 3

# Footer Menu
[[menu.footer]]
  name = "关于"
  weight = 1
  identifier = "about"
  url = "/about/"