baseurl = "https://kingwrcy.github.io/blog"
languageCode = "zh_cn"
title = "日积月累"
theme = "Hucore"
publishDir = "docs"
copyright = "&copy; 2018 |  <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
# disqusShortname = "shortname"
# googleAnalytics = "trackingcode"

[taxonomies]
tag = "tag"
category = "category"

[params]
description = "个人博客"
keywords = ["博客", "程序员", "上海"]
author = "JerryWang"
sharingicons = false

[params.highlight]
style = "github"
languages = ["go", "dockerfile","html","js","python","java"]

[[params.social]]
url = "https://github.com/kingwrcy"
fa_icon = "fa-github"

# [[params.social]]
# url = "https://gitlab.com/mgjohansen"
# fa_icon = "fa-gitlab"

# [[params.social]]
# url = "https://twitter.com/mgjohansen"
# fa_icon = "fa-twitter"

# [[params.social]]
# url = "https://linkedin.com/in/mgjohansen"
# fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

# [[params.socialshare]]
# url = "https://linkedin.com/in/mgjohansen"
# fa_icon = "fa-linkedin-square"
